### ISSUE TITLE
멤버 삭제(회원 탈퇴) JPA로 구현하기

### ISSUE THREAD

**Issue by Julienjang** [tutorLink-SYU-Capstone2023/Backend#15]
## Description 💭
회원 탈퇴 기능 구현하기

## To-do ✔️
- [x] 회원 탈퇴 기능 구현
- [x] 회원 상태를 'A' (Active)에서 'D' (Deleted)로 변경
- [x] SecurityContextHolder를 사용하여 사용자 로그인 정보를 지움

## ETC 🌷
- 회원 탈퇴 시 회원 상태를 'D'로 변경하여 회원을 비활성화 상태로 만듭니다.
- 사용자 로그인 정보를 지우고, 홈페이지로 리디렉션합니다.

**Comment by kokojihye** [comment]
최고최고.. 빠르네요👍🏻😁

**Comment by kimsquid110** [comment]
디테일한 설명 감사합니다 👍
